include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    dead_code: error
    deprecated_member_use: warning
    override_on_non_overriding_member: error

linter:
  rules:
    # Estilo de código
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
    - avoid_print
    - curly_braces_in_flow_control_structures
    
    # Buenas prácticas
    - always_declare_return_types
    - type_init_formals
    - avoid_relative_lib_imports
    - prefer_final_fields
    - unnecessary_null_checks
    
    # Flutter específico
    - prefer_const_constructors_in_immutables
    - avoid_shadowing_type_parameters
    - use_build_context_synchronously
    
    # Arquitectura
    - avoid_classes_with_only_static_members
    - depend_on_referenced_packages
